DROP TABLE IF EXISTS booking_statuses,
requests,
bookings,
comments,
items,
users;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR,
    requestor BIGINT REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    available BOOLEAN,
    user_id BIGINT REFERENCES users(user_id),
    request_id BIGINT REFERENCES requests(request_id),
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time timestamp,
    end_time timestamp,
    status VARCHAR(50),
    item_id BIGINT REFERENCES items(item_id),
    --owner_id BIGINT REFERENCES users(user_id),
    booker_id BIGINT REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    item_id BIGINT REFERENCES items(item_id),
    author_id BIGINT REFERENCES users(user_id),
    created timestamp
);

